// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: proto/ddns_service.proto

package ddns_server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartBeatClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *HeartBeatClient) Reset() {
	*x = HeartBeatClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ddns_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatClient) ProtoMessage() {}

func (x *HeartBeatClient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ddns_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatClient.ProtoReflect.Descriptor instead.
func (*HeartBeatClient) Descriptor() ([]byte, []int) {
	return file_proto_ddns_service_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeatClient) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ddns_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ddns_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_proto_ddns_service_proto_rawDescGZIP(), []int{1}
}

func (x *HeartBeat) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_proto_ddns_service_proto protoreflect.FileDescriptor

var file_proto_ddns_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x64, 0x6e, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x64, 0x6e, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x0f, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x1b,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x32, 0x59, 0x0a, 0x0a, 0x44,
	0x64, 0x6e, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0f, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x64,
	0x64, 0x6e, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x64, 0x64, 0x6e,
	0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x64, 0x64, 0x6e, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ddns_service_proto_rawDescOnce sync.Once
	file_proto_ddns_service_proto_rawDescData = file_proto_ddns_service_proto_rawDesc
)

func file_proto_ddns_service_proto_rawDescGZIP() []byte {
	file_proto_ddns_service_proto_rawDescOnce.Do(func() {
		file_proto_ddns_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ddns_service_proto_rawDescData)
	})
	return file_proto_ddns_service_proto_rawDescData
}

var file_proto_ddns_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ddns_service_proto_goTypes = []interface{}{
	(*HeartBeatClient)(nil), // 0: ddns_server.HeartBeatClient
	(*HeartBeat)(nil),       // 1: ddns_server.HeartBeat
}
var file_proto_ddns_service_proto_depIdxs = []int32{
	0, // 0: ddns_server.DdnsServer.HeartBeatServer:input_type -> ddns_server.HeartBeatClient
	1, // 1: ddns_server.DdnsServer.HeartBeatServer:output_type -> ddns_server.HeartBeat
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ddns_service_proto_init() }
func file_proto_ddns_service_proto_init() {
	if File_proto_ddns_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ddns_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ddns_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ddns_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ddns_service_proto_goTypes,
		DependencyIndexes: file_proto_ddns_service_proto_depIdxs,
		MessageInfos:      file_proto_ddns_service_proto_msgTypes,
	}.Build()
	File_proto_ddns_service_proto = out.File
	file_proto_ddns_service_proto_rawDesc = nil
	file_proto_ddns_service_proto_goTypes = nil
	file_proto_ddns_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DdnsServerClient is the client API for DdnsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DdnsServerClient interface {
	HeartBeatServer(ctx context.Context, opts ...grpc.CallOption) (DdnsServer_HeartBeatServerClient, error)
}

type ddnsServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDdnsServerClient(cc grpc.ClientConnInterface) DdnsServerClient {
	return &ddnsServerClient{cc}
}

func (c *ddnsServerClient) HeartBeatServer(ctx context.Context, opts ...grpc.CallOption) (DdnsServer_HeartBeatServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DdnsServer_serviceDesc.Streams[0], "/ddns_server.DdnsServer/HeartBeatServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &ddnsServerHeartBeatServerClient{stream}
	return x, nil
}

type DdnsServer_HeartBeatServerClient interface {
	Send(*HeartBeatClient) error
	Recv() (*HeartBeat, error)
	grpc.ClientStream
}

type ddnsServerHeartBeatServerClient struct {
	grpc.ClientStream
}

func (x *ddnsServerHeartBeatServerClient) Send(m *HeartBeatClient) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ddnsServerHeartBeatServerClient) Recv() (*HeartBeat, error) {
	m := new(HeartBeat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DdnsServerServer is the server API for DdnsServer service.
type DdnsServerServer interface {
	HeartBeatServer(DdnsServer_HeartBeatServerServer) error
}

// UnimplementedDdnsServerServer can be embedded to have forward compatible implementations.
type UnimplementedDdnsServerServer struct {
}

func (*UnimplementedDdnsServerServer) HeartBeatServer(DdnsServer_HeartBeatServerServer) error {
	return status.Errorf(codes.Unimplemented, "method HeartBeatServer not implemented")
}

func RegisterDdnsServerServer(s *grpc.Server, srv DdnsServerServer) {
	s.RegisterService(&_DdnsServer_serviceDesc, srv)
}

func _DdnsServer_HeartBeatServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DdnsServerServer).HeartBeatServer(&ddnsServerHeartBeatServerServer{stream})
}

type DdnsServer_HeartBeatServerServer interface {
	Send(*HeartBeat) error
	Recv() (*HeartBeatClient, error)
	grpc.ServerStream
}

type ddnsServerHeartBeatServerServer struct {
	grpc.ServerStream
}

func (x *ddnsServerHeartBeatServerServer) Send(m *HeartBeat) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ddnsServerHeartBeatServerServer) Recv() (*HeartBeatClient, error) {
	m := new(HeartBeatClient)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DdnsServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ddns_server.DdnsServer",
	HandlerType: (*DdnsServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HeartBeatServer",
			Handler:       _DdnsServer_HeartBeatServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/ddns_service.proto",
}
